#!/bin/sh
USER=root
HOST=ggchd.xyz
DIR=/var/www/mysite

hugo && rsync -avz --delete public/ ${USER}@${HOST}:${DIR} # this will delete everything on the server that's not in the local public folder 

exit 0
